# Generated by Django 5.2.7 on 2025-11-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
    ]
