# Generated by Django 5.2.7 on 2025-11-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_role_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principal',
            new_name='user',
        ),
    ]
