# Generated by Django 5.2.7 on 2025-11-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_principal_school_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='user',
            new_name='principal',
        ),
    ]
